# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2


    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        auto-update-conda: true

    - name: Install dependencis and build
      shell: bash -l {0}
      run: |
        # Create env for build
        conda update -n base -c defaults conda -y
        conda create -q -n testenv python=${{ matrix.python-version }} numpy setuptools_scm setuptools_scm_git_archive c-compiler -c conda-forge
        conda activate testenv
        pip install --no-deps .
        # Install additional test dependencies
        conda install flake8 pytest pytest-flake8 healpy -c conda-forge
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        conda activate testenv
        cd tests
        pytest
